// Dummy DB for all vendor dashboard pages
export const dummyDB = {
  vendors: [
    {
      vendorId: 'vendor123',
      businessName: 'Bloom Decorations',
      profilePhoto: '/profile_photo_sample.jpg',
      email: 'vendor@email.com',
      phone: '+1234567890',
      ownerName: 'Ayesha Khan',
      profileCompleted: true,
      location: {
        address: '123 Main St',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        zipCode: '54000',
      },
      facebook: 'https://facebook.com/bloomdecor',
      instagram: 'https://instagram.com/bloomdecor',
      website: 'https://bloomdecor.com',
      halalCert: null, // or { name: 'halal_cert.pdf' }
      stats: {
        bookings: 24,
        totalRevenue: 120000,
        avgRating: 4.8,
        profileViews: 1234,
      },
      analytics: {
        revenueByMonth: [
          { month: 'Jan', revenue: 10000 },
          { month: 'Feb', revenue: 12000 },
          { month: 'Mar', revenue: 15000 },
          { month: 'Apr', revenue: 18000 },
          { month: 'May', revenue: 20000 },
          { month: 'Jun', revenue: 25000 },
        ],
        bookingsByMonth: [
          { month: 'Jan', bookings: 2 },
          { month: 'Feb', bookings: 3 },
          { month: 'Mar', bookings: 4 },
          { month: 'Apr', bookings: 5 },
          { month: 'May', bookings: 5 },
          { month: 'Jun', bookings: 5 },
        ],
        clientVisits: [
          { month: 'Jan', visits: 100 },
          { month: 'Feb', visits: 120 },
          { month: 'Mar', visits: 150 },
          { month: 'Apr', visits: 180 },
          { month: 'May', visits: 200 },
          { month: 'Jun', visits: 250 },
        ],
        inquiryToBookingRate: 0.45,
        avgResponseTime: 2.1,
        profileViewsByCountry: [
          { country: 'Pakistan', value: 60 },
          { country: 'United States', value: 20 },
          { country: 'Canada', value: 10 },
          { country: 'Other', value: 10 },
        ],
        popularServices: [
          { service: 'Catering', count: 12 },
          { service: 'Decor', count: 8 },
          { service: 'Baking', count: 5 },
          { service: 'Events', count: 7 },
          { service: 'Wedding', count: 10 },
        ],
      },
      recentBookings: [
        {
          id: 'booking1',
          clientName: 'Ahmad Ali Butt',
          event: 'Wedding',
          date: '2025-01-02',
          status: 'Confirmed',
          amount: 32000,
          clientLocation: 'Lahore',
          clientPhone: '+923001234567',
          rating: 5,
          package: 'Gold',
          guests: 200,
          eventLocation: 'Pearl Banquet',
          eventDate: '2025-01-02',
          additionalDetails: 'VIP guest',
          paymentMethod: 'Bank Transfer',
        },
        {
          id: 'booking2',
          clientName: 'Sara Malik',
          event: 'Birthday',
          date: '2025-02-10',
          status: 'Pending',
          amount: 15000,
          clientLocation: 'Karachi',
          clientPhone: '+923008765432',
          rating: 4,
          package: 'Silver',
          guests: 50,
          eventLocation: 'Home',
          eventDate: '2025-02-10',
          additionalDetails: '',
          paymentMethod: 'Cash',
        },
      ],
      invoices: [
        {
          id: 'inv1',
          invoiceNumber: 'INV-001',
          clientName: 'Ali Khan',
          event: 'Wedding',
          date: '2024-06-01',
          dueDate: '2024-06-10',
          amount: 5000,
          status: 'Pending',
        },
        {
          id: 'inv2',
          invoiceNumber: 'INV-002',
          clientName: 'Sara Malik',
          event: 'Birthday',
          date: '2024-06-05',
          dueDate: '2024-06-15',
          amount: 15000,
          status: 'Paid',
        },
        {
          id: 'inv3',
          invoiceNumber: 'INV-003',
          clientName: 'Ahmad Ali Butt',
          event: 'Wedding',
          date: '2024-06-10',
          dueDate: '2024-06-20',
          amount: 32000,
          status: 'Overdue',
        },
      ],
      recentReviews: [
        {
          id: 'review1',
          clientName: 'Joha Dew',
          text: 'Amazingly beautiful photography services...',
          stars: 5,
          date: '2024-06-01',
        },
      ],
      pendingInquiries: [
        {
          id: 'inq1',
          clientName: 'Lisa',
          inquiry: 'Photography inquiry',
          date: '2024-06-02',
        },
      ],
      listings: [
        {
          id: 'listing1',
          name: 'Wedding Photography',
          price: 160,
          status: 'Active',
          coverImages: ['/hero_bg_blur.png'],
          businessInfo: 'Bloom Decorations',
          photoGallery: ['/hero_bg_blur.png'],
          description: 'Professional wedding photography',
          markets: 'Lahore',
          packages: 'Gold, Silver',
          services: 'Photography',
          faqs: 'What is included?',
          reviews: '5 stars',
          preferredVendors: 'None',
          automatedHellos: 'Hello!',
        },
      ],
    },
    // Add more vendors if needed
  ],
};

export function getVendorById(id) {
  return dummyDB.vendors.find(v => v.vendorId === id);
} 